set(ZEGO_EXPRESS_DLL "${ZEGO_EXPRESS_LIBRARY_PATH}/ZegoExpressEngine.dll")
set(TARGET_BIN_DIR "${CMAKE_CURRENT_BINARY_DIR}/${CMAKE_CFG_INTDIR}")

add_custom_command(
    TARGET ${EXECUTABLE_NAME} POST_BUILD 
    COMMAND ${CMAKE_COMMAND} -E copy_if_different ${ZEGO_EXPRESS_DLL} ${TARGET_BIN_DIR}
    COMMAND ${CMAKE_COMMAND} -E echo "[ZEGO] Copy ${ZEGO_EXPRESS_DLL} to ${TARGET_BIN_DIR}"
)
